name: Build and Deploy to Development

on:
  push:
    branches: [ development_server ]

jobs:
  build-images-and-push-to-ecr:
    name: Build Docker Images and Push to ECR
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ap-south-1
          role-session-name: github-actions-session

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT


      - name: Build, tag, and push the backend image to Amazon ECR
        id: build-backend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "visitors-logs-systems/backend"
          IMAGE_TAG: "dev-${{ steps.vars.outputs.SHORT_SHA }}"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.backend .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push the frontend image to Amazon ECR
        id: build-frontend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "visitors-logs-systems/frontend"
          IMAGE_TAG: "dev-${{ steps.vars.outputs.SHORT_SHA }}"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.frontend .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
  
  build-ami:
    needs: build-images-and-push-to-ecr
    name: Build AWS AMI using Packer
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ap-south-1
          role-session-name: github-actions-session

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Generate Packer variables file
        run: |
          cat > ./packer/variables.auto.pkrvars.hcl <<EOF
          region      = "ap-south-1"
          instance_type = "${{ secrets.INSTANCE_TYPE }}"
          tag_name    = "${{ needs.build-images-and-push-to-ecr.outputs.SHORT_SHA }}"
          environment = "dev"
          ecr_registry: ${{ steps.login-ecr.outputs.registry }}
          img_tag: "dev-${{ steps.vars.outputs.SHORT_SHA }}"
          EOF

      - name: Initialize Packer plugins
        working-directory: ./packer
        run: packer init visitor-logs-system-ami.pkr.hcl

      - name: Validate Packer template
        working-directory: ./packer
        run: packer validate -var-file=variables.auto.pkrvars.hcl visitor-logs-system-ami.pkr.hcl

      - name: Build AWS AMI (packer) and capture AMI id
        working-directory: ./packer
        id: packer_build
        run: |
          set -euo pipefail
          packer build -machine-readable -var-file=variables.auto.pkrvars.hcl \
            ./visitor-logs-system-ami.pkr.hcl | tee /tmp/packer.out
          AMI_LINE=$(awk -F, '/artifact,0,id/ { print $6 }' /tmp/packer.out | tail -n1)
          AMI_ID="${AMI_LINE#*:}"
          echo "ami_id=${AMI_ID}" >> $GITHUB_OUTPUT

  dispatch-to-external:
    needs: build-ami
    name: Dispatch to External Repository with AMI ID
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event with AMI
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
          repository: m-bilalkhan/visitor-log-system-iac
          event-type: deploy-to-dev
          client-payload: |
            {
              "sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}",
              "ami": "${{ needs.build-images-and-ami.outputs.ami_id }}"
            }
      - name: AMI ID
        run: echo "${AMI_ID}"
